# Generated by Django 5.1.1 on 2024-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicspending',
            name='temporary_field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
