# Generated by Django 5.1.1 on 2024-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparify', '0002_publicspending_temporary_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicspending',
            name='temporary_field',
        ),
        migrations.AddField(
            model_name='citizen',
            name='temporary_field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
